export type Thread = {
  slug: string;
  title: string;
  description: string;
  published: string;
  sharingHeadline: string;
  paragraphs: readonly string[];
  emphasizeQuestion?: boolean;
};

// Add new articles here. Pages, metadata, sharing images and sitemap entries
// are generated from this content at build time.
export const threads: readonly Thread[] = [
  {
    slug: "what-if-ai-stops-being-the-cheap-option",
    title: "What if AI stops being the cheap option?",
    description: "On the time and effort behind repeated AI attempts, the incentives of usage-based pricing, and knowing when to do a task yourself.",
    published: "2026-10-05",
    sharingHeadline: "What if AI stops\nbeing the\ncheap option?",
    emphasizeQuestion: true,
    paragraphs: [
      "I sometimes wonder how much of the way we use AI depends on what it costs right now.",
      "Suppose the tools you use became expensive enough that you had to think before opening them.",
      "Would you use them for the same things?",
      "And would you count the cost of the answer, or the cost of finally getting one you could use?",
      "Let’s say the first answer is wrong. You explain again. The second one misses something. You correct it. A few more attempts, and the eighth answer finally does what you wanted.",
      "You got there. But it took eight attempts, your explanations, and enough understanding of the task to recognise seven answers that weren’t good enough.",
      "If you were paying for every attempt, that would be the cost of getting the result.",
      "Even without that bill, you’ve spent time reading, checking and correcting.",
      "I think we sometimes overlook this when we talk about how useful a model is. Someone spends ten or twelve messages getting a simple task done and comes away impressed that the AI eventually managed it.",
      "I’d want to ask how long the task would have taken without it.",
      "Some work is complicated enough to deserve that back and forth. But if I’m repeatedly explaining a small change I could have made myself, I should probably notice when the explanation has become more work than the change.",
      "That’s also what makes me wonder about the business model.",
      "If a service earns more each time I try again, what incentive does it have to help me finish in fewer attempts? I’d want that question considered before repeated attempts become something we accept without thinking.",
      "I’m not predicting that every AI service will suddenly become unaffordable. A higher price might simply make us examine habits we’re currently comfortable with.",
      "We did things before these tools existed. Sometimes I think we forget that a little too quickly. Asking AI becomes the first step, even when we already know how to do the task.",
      "I’d still pay for help that saved me hours. I’d think twice about paying to spend twenty minutes explaining something I could have done in ten.",
      "If every attempt had a noticeable cost, when would you stop asking and do it yourself?",
    ],
  },
  {
    slug: "the-same-eyes-like-both",
    title: "The same eyes like both.",
    description: "On finding beauty in unsettling art and familiar scenery, and making room for the different things that catch our attention.",
    published: "2026-10-04",
    sharingHeadline: "The same eyes\nlike both.",
    emphasizeQuestion: true,
    paragraphs: [
      "Sometimes I joke that I could design a character for a horror movie.",
      "I like imagining something a little unsettling. A face with one detail that feels wrong. A shape you can’t quite understand. Something you’d look at twice, even if the second look made you uncomfortable.",
      "I enjoy that kind of art.",
      "Then there are the pictures I take.",
      "Sunrises. Sunsets. People, animals, scenery. Something familiar from an angle that makes me want to stop and look at it again.",
      "Put those interests beside each other and they might seem like they belong to different people.",
      "They feel quite natural together to me.",
      "I can find something interesting in a disturbing image, then spend time looking at the colours in an evening sky. I don’t feel much need to explain the change.",
      "But it makes me wonder what I’m actually drawn to.",
      "Sometimes it’s a mood. Sometimes it’s a detail I can’t stop looking at. Sometimes I couldn’t tell you why I took the picture, only that I wanted to keep what I was seeing.",
      "“Beautiful” feels like a small word for all of that.",
      "There are things I enjoy looking at that I wouldn’t want anywhere near me. There are ordinary things I’d happily photograph again tomorrow, even though I already have several pictures of them.",
      "I like having room for both.",
      "It would be strange to walk past something that caught my attention because it didn’t match the rest of what I liked.",
      "Maybe a collection of those things would introduce me better than a few words could. You’d see what I kept stopping for, and probably have a few questions.",
      "Would everything that catches your eye look like it belonged to the same person?",
    ],
  },
  {
    slug: "i-dont-like-it-anymore-nothing-changed",
    title: "I don’t like it anymore. Nothing changed.",
    description: "On revisiting old designs, changing taste and learning to tell the difference between creative growth and following what we see around us.",
    published: "2026-10-03",
    sharingHeadline: "I don’t like it\nanymore.\nNothing changed.",
    emphasizeQuestion: true,
    paragraphs: [
      "You find an old design in a folder.",
      "You remember choosing those colours. Moving that heading around. Finally looking at it and thinking, yes, this feels right.",
      "Now you open it and wonder why you made half those decisions.",
      "The strange part is that nothing happened to the design while you were away. It’s exactly what you left there.",
      "Something happened to the person looking at it.",
      "Maybe you’ve learned more. You notice spacing you couldn’t see before. You understand why the page feels crowded. You can explain what you’d change.",
      "That sounds like growing.",
      "But sometimes the explanation is harder to find. You just don’t like it anymore.",
      "I wonder how much of that comes from what we’ve been looking at recently. Spend a few weeks seeing the same kind of typography, colours and layouts, and something you once liked can start feeling wrong.",
      "Would you have wanted to change it if you hadn’t seen those other things?",
      "I don’t think being influenced is a problem. We’re going to change as we see more of the world. But I’d like to understand what changed, rather than immediately assume my old choices were bad.",
      "Maybe that design had something I’ve stopped appreciating. Maybe it really does need work.",
      "Before replacing everything, I think it’s worth remembering why it felt right the first time.",
      "How do you know when your taste is growing, and when it’s just following?",
    ],
  },
  {
    slug: "youve-been-collecting-ideas-without-noticing",
    title: "You’ve been collecting ideas without noticing.",
    description: "On developing an eye for ideas in everyday life, building a library of references, and why creative judgment still matters alongside AI tools.",
    published: "2026-10-02",
    sharingHeadline: "You’ve been\ncollecting ideas\nwithout noticing.",
    paragraphs: [
      "You might notice the way light hits a building on your way to work. A strange typeface on a poster. The shape of a car light. The way a scene in a movie is framed, or how an animation moves while you’re scrolling.",
      "Most people see these things too.",
      "I think the difference is in what you take from them.",
      "There’s a skill in noticing something good before someone tells you it is good. In seeing a colour, shape, movement or composition and knowing there is something worth keeping there, even if you don’t know where you’ll use it yet.",
      "And I don’t think every creative person automatically has that.",
      "You can know every design tool. You can understand grids, typography, motion and code. But noticing is different.",
      "Do it for long enough and you start building this strange library in your head. Colours, shapes, interfaces, buildings, objects, movements and random moments you probably don’t even remember seeing.",
      "Then one day, something comes back.",
      "Not exactly as you saw it. You take the part that mattered, change it, combine it with something else and make it your own.",
      "That’s why Codex skills, Claude skills, prompts, or whatever comes next don’t really replace this.",
      "They can generate hundreds of directions. They can give you references and help you build faster.",
      "But they can’t automatically give you the eye to know what is worth taking from them.",
      "Two people can see the exact same output. One sees nothing special. The other notices one tiny detail and turns it into something completely different.",
      "Maybe one of the hardest creative skills isn’t making more.",
      "It’s seeing better.",
      "Knowing what deserves your attention, what should stay in your head, and what is worth carrying with you until the right moment comes.",
      "What did you notice recently that everyone else probably walked past?",
    ],
  },
  {
    slug: "maybe-we-needed-permission-to-see-it",
    title: "Maybe we needed permission to see it.",
    description: "On reputation, creative judgment and how knowing who made something can change the time and attention we give their work.",
    published: "2026-10-01",
    sharingHeadline: "Maybe we needed\npermission\nto see it.",
    paragraphs: [
      "Imagine opening a website made by a student you’ve never heard of.",
      "The navigation is unusual. The heading takes up almost the whole screen. There’s an animation you don’t completely understand.",
      "You might look at it for a few seconds and think they’re trying too hard.",
      "Now imagine finding out the exact same website was made by a famous design studio.",
      "Nothing changed. Same typography. Same animation. Same strange navigation.",
      "But I wonder if you would stay a little longer.",
      "Maybe the heading starts feeling bold instead of excessive. Maybe you replay the animation because there must be a reason for it. Something that felt unnecessary a minute ago suddenly feels intentional.",
      "I keep thinking about why that happens.",
      "I understand that reputation has to mean something. A studio builds its name through years of good work, and that gives us a reason to trust its decisions. If they do something strange, we’re more willing to assume there’s an idea behind it.",
      "But that creates an interesting problem for someone who doesn’t have that name yet.",
      "You need people to take your work seriously to build a reputation. But sometimes it feels like you need the reputation before people are willing to take the work seriously.",
      "Design makes this especially strange because not everything has an obvious right answer. We can check whether the text is readable or whether the navigation works. But deciding whether something is creative, unnecessary, brilliant or just weird is much less certain.",
      "And maybe knowing who made it changes how much time we give ourselves to decide.",
      "You might scroll past something today, then see it again tomorrow with an award beside it and go back for another look. You notice details you didn’t notice before. You start looking for the thinking behind them.",
      "The work was already there.",
      "Maybe reputation doesn’t make an idea better. Maybe it just gives the idea more time to prove itself.",
      "If an unknown student made your favourite piece of work from a famous studio, would you have looked at it long enough to love it?",
    ],
  },
  {
    slug: "human-made-might-become-a-luxury",
    title: "Human-made might become a luxury.",
    description: "On AI, human effort and why evidence that someone paid attention might become the most valuable part of a digital experience.",
    published: "2026-09-30",
    sharingHeadline: "Human-made\nmight become\na luxury.",
    paragraphs: [
      "You pick up a shirt. You like the colour. It fits.",
      "Then you check the label.",
      "“100% cotton.”",
      "A few words, but somehow they change how you feel about it. You want to know what you’re wearing, even when the difference wasn’t obvious a moment ago.",
      "I wonder whether we’ll start checking websites like that.",
      "We get excited when something makes life easier. Cheaper materials. Food ready in minutes. Things we can produce faster and buy without thinking too much.",
      "But somewhere alongside that convenience, words like “handmade” and “home-cooked” become reasons to choose something.",
      "Maybe AI will have its own version of this.",
      "Right now, watching a prompt turn into a website feels impressive. A few sentences become a layout, images, buttons, even a working product. I understand the excitement. I use these tools too.",
      "But imagine seeing that same kind of website hundreds of times. Different names, familiar layouts, the same polished sentences saying very little.",
      "Eventually, “I made this in five minutes” might stop being the interesting part.",
      "Someone might ask why the website looks that way. Whether the designer understood their business. Whether anyone watched a customer struggle with the booking form before deciding it was finished.",
      "That’s where I think the work will still matter.",
      "A developer can use AI and spend hours getting one interaction right. A designer can generate options and reject every one because none of them feels right for the brand. The tool can be part of a thoughtful process.",
      "I can imagine “human-made” becoming a selling point. Although I’d still want to look closer. Someone typing every line themselves doesn’t automatically mean they cared about the result.",
      "Maybe what we’ll really want is evidence that someone paid attention.",
      "When making something becomes almost effortless, will knowing that someone made an effort become part of its value?",
    ],
  },
  {
    slug: "someone-designed-your-idea-of-expensive",
    title: "Someone designed your idea of expensive.",
    description: "On the visual cues that make something feel premium, the expectations websites create, and what happens when a brand has to live up to them.",
    published: "2026-09-29",
    sharingHeadline: "Someone designed\nyour idea of\nexpensive.",
    paragraphs: [
      "Imagine a small bottle of perfume on a white page.",
      "There’s one photograph. A name you’re not sure how to pronounce. Plenty of empty space. You have to scroll to find the price.",
      "You’re already expecting it to cost a lot.",
      "Now picture that same bottle inside a bright product card. Five stars, three badges, a crossed-out price, and a countdown above “BUY NOW.”",
      "Suddenly, you’re looking for a deal.",
      "I find that a little uncomfortable. We haven’t smelled anything yet.",
      "Somewhere along the way, we learned to associate certain typefaces, colours, and layouts with certain kinds of value. A brand can borrow those visual cues before it has earned any trust.",
      "That gives designers an interesting amount of power.",
      "In web development, we turn those cues into behaviour. We decide how slowly a product reveals itself, how much screen space a photograph deserves, and whether a button asks politely or practically shouts.",
      "Even the mobile layout carries those decisions. Squeeze everything together to fit the screen, and the carefully composed brand might start feeling like a completely different business.",
      "But there’s a limit to what all that presentation can hold up.",
      "Eventually, someone receives the bottle. Uses the product. Tries to get help. The experience starts answering the expectations the website created.",
      "I think that’s where branding gets interesting: when you have to live up to the feeling you designed.",
      "How much of what you call “premium” comes from the thing itself, and how much comes from the way you were introduced to it?",
    ],
  },
  {
    slug: "it-works-why-cant-i-leave-it-alone",
    title: "It works. Why can’t I leave it alone?",
    description: "On frontend details, perfectionism and learning when another adjustment makes the work better, and when it’s time to close the laptop.",
    published: "2026-09-29",
    sharingHeadline: "It works.\nWhy can’t I\nleave it alone?",
    paragraphs: [
      "You’re about to close the laptop.",
      "Then you notice it. The heading feels slightly too far from the paragraph.",
      "You move it up. Now the button underneath looks awkward. You adjust that too. Somewhere along the way, you decide the animation needs another look.",
      "You were finished forty minutes ago.",
      "I think frontend work attracts this kind of attention. You’re building something people can see, touch, and react to. Even when the code works, there’s still the question of how it feels.",
      "A menu can open correctly and feel clumsy. Text can be readable and still tiring to get through. A button can look good until someone tries to use it on a smaller screen.",
      "Caring about those things makes the work better. Sometimes a tiny adjustment really is worth the time.",
      "The difficult part is knowing when you’ve crossed into fixing things because you can’t bear to call them finished.",
      "You change a value, stare at it, then change it back. You’ve looked at the page for so long that you’re no longer sure which version feels right.",
      "I understand why people connect good frontend work with perfectionism. The details are visible. Once you notice something, it can be difficult to ignore.",
      "But I wonder whether getting better also means learning when to stop.",
      "Someone using the page might still be struggling to find what they need while I’m deciding whether a shadow is slightly too dark. That thought brings things back into perspective.",
      "I want to keep the part of me that notices. I also want to get better at deciding what deserves another hour.",
      "Maybe closing the laptop is part of the work too. Leave it overnight. Come back. See whether the thing bothering you still matters.",
      "How do you know when you’re making something better, and when you’re just finding it difficult to let go?",
    ],
  },
  {
    slug: "what-if-we-stop-having-something-to-say",
    title: "What if we stop having something to say?",
    description: "A reflection on AI, creative patience and the small effort of finding our own words before asking a tool what to say.",
    published: "2026-09-28",
    sharingHeadline: "What if we stop\nhaving something\nto say?",
    paragraphs: [
      "Imagine writing a birthday message for someone you’ve known for ten years.",
      "You open AI.",
      "A few seconds later, the message is ready. Warm, thoughtful, all the right words. You send it.",
      "But somewhere in those ten years, there was probably a terrible joke, a difficult evening, or something only the two of you would understand. You never stopped to remember it.",
      "I wonder what happens if we keep skipping that small effort of looking inside ourselves.",
      "We have help with almost everything now. What to write. What to draw. How to explain a feeling. I understand the appeal. Sometimes you’re tired, stuck, or need somewhere to begin.",
      "But what if asking becomes our first response to everything?",
      "Before sitting with a question. Before making an awkward attempt. Before noticing something for ourselves.",
      "J.K. Rowling says the idea for Harry Potter came to her during a delayed train journey in 1990. She then spent years developing and writing it. I keep thinking about that distance between a thought on a train and a world that millions of people could imagine.",
      "Or take Stan Lee and Jack Kirby creating the Fantastic Four in 1961. Something we now recognise as part of a huge fictional universe was once work being figured out and put onto comic pages.",
      "It makes me wonder how many ideas need time to become interesting. How many we might abandon because an instant answer already looks good enough.",
      "A tree outside your window changes slowly. An evening sky lasts a few minutes. Neither comes with a summary explaining why you should care. You have to give it some attention.",
      "I worry we might become impatient with things that take that long. Including our own thoughts.",
      "In creative work, I can imagine generating twenty directions before knowing what I wanted to explore. Choosing becomes easier. Knowing why I chose something still takes effort.",
      "There’s plenty I’d happily let a tool help me build. I still want to bring something of my own to it.",
      "Maybe that means keeping a few small habits. Trying the sentence myself. Looking outside. Following an idea for a while before asking for a better one.",
      "If we get used to asking AI what to say, what happens to the things we would only discover by trying to say them ourselves?",
    ],
  },
  {
    slug: "how-much-of-this-actually-happened",
    title: "How much of this actually happened?",
    description: "On the stories we build around short messages, seen labels and typing indicators, and what those assumptions mean for the people designing interfaces.",
    published: "2026-09-26",
    sharingHeadline: "How much of this\nactually happened?",
    paragraphs: [
      "Someone replies, “Okay.”",
      "You look at it again.",
      "Are they annoyed? Did you say something wrong? Usually they add something else. Maybe you should read your last message one more time.",
      "A few minutes later, they call. They sound completely normal. They were busy.",
      "Meanwhile, you’ve already had an argument with them in your head.",
      "I find that strange. How quickly we can take a small piece of information and build a whole situation around it. The message gave us one word. We supplied the voice, the expression, and the meaning.",
      "And for a moment, our version felt convincing.",
      "Maybe our minds are doing their own kind of blended reality. What’s happening gets mixed with what we expect, what happened before, and what we’re worried might happen next.",
      "We can feel the effects before we’ve checked whether the story is true.",
      "Technology gives us plenty of little gaps to fill. A typing indicator appears, then disappears. Someone reads a message without replying. A location stops updating.",
      "We know what the interface shows us. Why it happened is often something we invent.",
      "That’s an uncomfortable thought when you’re the person building the interface. A “seen” label looks like a small, useful feature. But someone might spend the next hour wondering why they were left there.",
      "We can’t predict every interpretation. Still, it makes me want to think more carefully about what a status actually tells people, and what it quietly encourages them to assume.",
      "I like the idea of the mind as a blended reality system. I’m less comfortable with how easily I can forget which parts I added myself.",
      "When was the last time you reacted to something your mind filled in?",
    ],
  },
  {
    slug: "why-do-we-save-things-we-never-return-to",
    title: "Why do we save things we never return to?",
    description: "A reflection on saved places, memories and the people behind them, and the quiet assumption built into every bookmark button: that we’ll come back.",
    published: "2026-09-25",
    sharingHeadline: "Why do we save\nthings we never\nreturn to?",
    paragraphs: [
      "Somewhere in your phone, there might be a place you saved for two people.",
      "A small café. A beach. Somewhere someone once said, “We should go there.”",
      "You saved it because you meant to.",
      "Then life got busy. Maybe you lost touch. The place is still sitting between a recipe you never tried and a screenshot you no longer understand.",
      "If you opened it now, you might barely notice the place. You’d remember who you wanted to take.",
      "I wonder how many things we save like that.",
      "A song to send someone. A photo we think they would laugh at. A message we keep because deleting it feels a little too final.",
      "Somewhere along the way, the things we saved for later became memories.",
      "We save the best things for a day when we’ll have more time, enough money, or the right person beside us. “Someday” feels safe. We rarely stop to ask whether that day will actually come.",
      "People change. We lose touch. Sometimes someone is gone before we get to share what we kept for them. The thing remains, carrying a meaning nobody else would know.",
      "When we design websites, we add bookmark buttons, little hearts, and favourites panels. We give people somewhere to keep things and a way to find them again.",
      "There’s a small assumption behind all of it: they’ll come back.",
      "Some will. Others might forget, feel differently, or never get the chance. A saved item can stay exactly where we left it while everything around it changes.",
      "It makes me think differently about that little button. Someone taps it, expecting a future moment when they’ll need what’s on the screen. We can build a way back to it. What happens between now and then is outside the interface.",
      "Maybe we’ll never open some of those things again. Maybe knowing they’re still there is enough.",
      "What have you kept that would look ordinary to everyone else, but means someone to you?",
    ],
  },
  {
    slug: "would-i-still-make-this-if-nobody-could-see-it",
    title: "Would I still make this if nobody could see it?",
    description: "On the satisfaction of making things, the pull of an audience, and whether the hope of a reaction starts choosing what we create next.",
    published: "2026-09-23",
    sharingHeadline: "Would I still\nmake this if nobody\ncould see it?",
    paragraphs: [
      "You publish something, close the tab, and get on with your day.",
      "A few minutes later, you’re back.",
      "Nothing yet.",
      "You tell yourself you’re checking whether everything looks right. It does. You check again anyway.",
      "I think there’s a slightly uncomfortable question hiding in that moment. How much of the excitement came from making it, and how much came from imagining someone’s reaction?",
      "While you’re working, it’s easy to forget about an audience. You’re trying to get something right. A transition feels too sudden. The spacing looks strange. You change a few things, try again, and finally it behaves the way you imagined.",
      "That feels good before anyone else sees it.",
      "Then you share it. Somehow, something you were happy with an hour ago starts feeling less impressive because nobody has said anything.",
      "The work hasn’t changed. But your relationship with it has.",
      "I don’t think wanting a reaction makes the effort less honest. When you spend time on something, it makes sense to hope someone notices. Sometimes a small comment is enough to make you want to keep going.",
      "What interests me is whether that hope starts choosing the next thing we make.",
      "Would you still try the strange idea? Would you spend an evening fixing a detail almost nobody will notice? Or would you pick something easier to explain, something you already know people like?",
      "I’m not sure there’s a clean answer. I’d like to think curiosity would keep me making things. Being seen probably matters to me too.",
      "But I wonder what I’d choose if, just for a while, there were no reactions to check.",
      "If nobody could ever see what you made, what would you keep making?",
    ],
  },
  {
    slug: "is-there-a-galaxy-inside-your-head",
    title: "Is there a galaxy inside your head?",
    description: "A reflection on memory, connected thoughts and imagining the mind as a galaxy, through the eyes of a designer who builds interfaces.",
    published: "2026-09-22",
    sharingHeadline: "Is there a galaxy\ninside your head?",
    paragraphs: [
      "You hear a song you haven’t heard in years.",
      "For a moment, you remember a room. Someone who used to sit beside you. A conversation you thought you’d forgotten. You were just choosing something to listen to, and somehow you ended up somewhere else.",
      "I find that strange. How one small thing can lead you through so much.",
      "Maybe that’s why I like the idea of the mind being a galaxy.",
      "Some thoughts feel close. You return to them every day. Others seem impossibly far away, until a familiar voice or an old photo brings them back. And then there are the ideas you haven’t quite reached yet. You can sense something there, but you don’t know what it is.",
      "Of course, a brain isn’t literally a galaxy. The comparison is a way to imagine something we can’t directly see.",
      "As someone who designs and builds interfaces, I find myself wondering what exploring that space would feel like. Would memories have locations? Could you follow a thought and discover what it connects to? Would getting lost be frustrating, or part of the experience?",
      "Even a simple website needs decisions about what appears first and what a person discovers next. Imagining a mind as a place makes those decisions much more interesting.",
      "I don’t think I’d arrange mine neatly. Some things would probably be unfinished. A few would be difficult to find. I might be surprised by what was still there.",
      "If someone could wander through your mind, what would they keep coming back to?",
    ],
  },
];

export const threadPath = (thread: Thread) => `/blogs/${thread.slug}`;
export const threadReadingTime = (thread: Thread) => `${Math.max(1, Math.ceil(thread.paragraphs.join(" ").split(/\s+/).length / 200))} min read`;
export const threadDate = (thread: Thread) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(thread.published));
export const getThread = (slug: string) => threads.find(thread => thread.slug === slug);
